name: Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this to the branch where you develop (default: 
'main')

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Ruby (required by Jekyll)
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5  # Adjust the Ruby version if necessary

      # Step 3: Install Jekyll and Bundler
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Step 4: Build the Jekyll site
      - name: Build site
        run: bundle exec jekyll build

      # Step 5: Deploy the _site directory to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

